#! /bin/sh

# check in linuxrc to /work/src/done/STABLE
# call from the linuxrc directory

ver=`cut -d. -f1-3 VERSION`
linuxrc=/tmp/linuxrc-$ver

if [ "$ver" = "" ] ; then
  echo "no version info?"
  exit 1
fi

echo "going to check in linuxrc version $ver..."

make clean
rm -rf $linuxrc
mkdir $linuxrc
tar -cf - * | tar -C $linuxrc -xf -
cd $linuxrc
find . -depth -name CVS -exec rm -r {} \;
find . -depth -name .cvsignore -exec rm -r {} \;
rm -f ci_linuxrc Makefile.new
cd /tmp

tar -jcf $linuxrc.tar.bz2 linuxrc-$ver

if mkdir /work/src/done/STABLE/linuxrc ; then
  cd /work/src/done/STABLE/linuxrc
  cp $linuxrc.tar.bz2 /work/SRC/all/linuxrc/linuxrc.{changes,spec} .
  [ -f /work/SRC/all/linuxrc/config-dist.sh ] && cp /work/SRC/all/linuxrc/config-dist.sh .
  perl -pi -e 's/^(Version:\s+)\S+/${1}'$ver'/' /work/src/done/STABLE/linuxrc/linuxrc.spec
  perl -pi -e 's/^(Source.+?-)\S+?(\.tar\.bz2)/${1}'$ver'${2}/' /work/src/done/STABLE/linuxrc/linuxrc.spec
  . /work/src/bin/.profile
  vc linuxrc
  rm /work/src/done/STABLE/linuxrc/*~
  echo "ok"
else
  echo oops
  exit 1
fi
