/*
  Automatically generated by 'make config' -- don't edit!
*/
#ifndef _PCMCIA_CONFIG_H
#define _PCMCIA_CONFIG_H

#define AUTOCONF_INCLUDED
#define __IN_PCMCIA_PACKAGE__

#define LINUX "/usr/src/linux"
#define PREFIX ""
#define KCC "cc"
#define UCC "cc"
#define LD "ld"
#define KFLAGS ""
#define UFLAGS ""
#define PCDEBUG ""
#define USE_PM 1
#undef  UNSAFE_TOOLS
#define CONFIG_CARDBUS 1
#undef  CONFIG_PNP_BIOS
#define MODDIR "/lib/modules/2.4.20-4GB"
#define PCMCIA_EXT_DIR "pcmcia"
#define PCMCIA_KRN_DIR ""
#define NETDIR "net"

/* Options from current kernel */
#define CONFIG_MODULES 1
#undef  CONFIG_PCMCIA
#undef  CONFIG_SMP
#undef  CONFIG_PREEMPT
#define CONFIG_PCI 1
#define CONFIG_PM 1
#define CONFIG_SCSI 1
#undef  CONFIG_IEEE1394
#define CONFIG_INET 1
#define CONFIG_NET_PCMCIA_RADIO 1
#define CONFIG_TR 1
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_DIVERT
#undef  CONFIG_MODVERSIONS
#undef  CONFIG_DEBUG_KERNEL
#undef  CONFIG_PREEMPT
#define CONFIG_PROC_FS 1
#define CONFIG_X86_L1_CACHE_BYTES 32
#define CONFIG_X86_L1_CACHE_SHIFT 5
#define CONFIG_PCI_QUIRKS 1
#undef  CONFIG_EISA
#define CONFIG_X86_CMPXCHG 1
#define CONFIG_1GB 1
#undef  CONFIG_2GB
#undef  CONFIG_3GB
#undef  CONFIG_RWSEM_GENERIC_SPINLOCK
#define CONFIG_RWSEM_XCHGADD_ALGORITHM 1
#define ARCH "i386"
#define HOST_ARCH "i386"
#define AFLAGS ""
#define CONFIG_ISA 1
#define CONFIG_UID16 1

#define UTS_RELEASE "2.4.20-4GB"
#define UTS_VERSION "#1 Tue Feb 18 08:00:27 UTC 2003"
#define LINUX_VERSION_CODE 132116
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

#define HAS_PROC_BUS 1
#undef  NEW_AIC7XXX
#undef  OLD_AIC7XXX
#define AIC7XXX_H <../drivers/scsi/aic7xxx_old/aic7xxx.h>
#define SYSV_INIT 1
#define RC_DIR "/etc/init.d"
#undef  HAS_FORMS
#define HAS_XAW 1
#undef  HAS_GTK
#define HAS_WORDEXP 1
#define MANDIR "/usr/share/man/"
#define XMANDIR "/usr/X11R6/man/"

#endif /* _PCMCIA_CONFIG_H */
