/*
  Automatically generated by 'make config' -- don't edit!
*/
#ifndef _PCMCIA_CONFIG_H
#define _PCMCIA_CONFIG_H

#define AUTOCONF_INCLUDED

#define LINUX "/usr/src/linux"
#define PREFIX ""
#define MODDIR "/lib/modules/2.2.14"
#define KFLAGS ""
#define UFLAGS ""
#define PCDEBUG ""
#define USE_APM 1
#undef  UNSAFE_TOOLS
#define CONFIG_CARDBUS 1
#define CONFIG_PNP_BIOS 1

#undef  CONFIG_SMP
#define CONFIG_PCI 1
#define CONFIG_PCI_QUIRKS 1
#undef  CONFIG_APM
#define CONFIG_SCSI 1
#define CONFIG_INET 1
#define CONFIG_NET_RADIO 1
#define CONFIG_TR 1
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_MODVERSIONS
#define CONFIG_PROC_FS 1
#define CONFIG_1GB 1
#undef  CONFIG_2GB
#undef  CONFIG_3GB
#undef  CONFIG_SMP
#define CONFIG_PCI 1
#define CONFIG_PCI_QUIRKS 1
#undef  CONFIG_APM
#define CONFIG_SCSI 1
#define CONFIG_INET 1
#define CONFIG_NET_RADIO 1
#define CONFIG_TR 1
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_MODVERSIONS
#define CONFIG_PROC_FS 1
#define CONFIG_1GB 1
#undef  CONFIG_2GB
#undef  CONFIG_3GB
#define CONFIG_ISA 1

#define UTS_RELEASE "2.2.14"
#define UTS_VERSION "#1 Fri Feb 4 10:58:11 CET 2000"
#define LINUX_VERSION_CODE 131598

#define HAS_PROC_BUS 1
#define HAS_WIRELESS_EXTENSIONS 1
#define SYSV_INIT 1
#undef  INSTALL_DEPMOD
#undef  HAS_FORMS

#endif /* _PCMCIA_CONFIG_H */
