#! /usr/bin/perl

# add a new text message

die "usage: add_text id english_text\n" if @ARGV != 2;

$id = shift;
$text = shift;

for $f (<*.txt>) {
  if(open F, $f) {
    @f = (<F>);
    close F;

    for (@f) { s/\}$/},/ }

    while($f[-1] !~ /\};/ && @f > 1) {
      pop @f;
    }
    pop @f;

    push @f, sprintf("{ %-19s %-55s }\n", "$id,", "\"$text\"");
    push @f, "};\n";

    die "oops: format error in \"$f\"\n" if @f < 20;

    if(open F, ">$f") {
      print F @f;
      close F;
    }
  }
}

